basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(),name='delete'),
] 

cbvTopic/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name 

basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy

# Create your views here.
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("<h1>Class based views are cool !</h1>")

class IndexView(TemplateView):
    template_name = 'index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme']= 'Basic Injection !'
#         return context


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School
    template_name = 'school_form.html'

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School
    template_name = 'school_form.html'

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")
    template_name = 'school_confirm_delete.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <!-- n%7)8v(@!&2a9u2(j30@9aw1v-d8*84j2!s2t%bh#bh2m+-ywo -->
                <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item active"><a class="nav-link" href="#">Maybe..</a></li>

            </ul>

        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
    
</body>
</html>

templates/basicApp_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item active"><a class="nav-link" href="#">Maybe...</a></li>

            </ul>

        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
    
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <!-- <h1>Hello. This is index. Now using template view.</h1>
    <h2>Injected Content: {{ injectme }}</h2> -->
    <div class="jumbotron">
        <h1>Home Page !</h1>
    </div>
{% endblock %}

templates/school_confirm_delete.html
{% extends "basicApp_base.html" %}
{% block body_block %}

<h1>Delete: {{school.name}}? </h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

templates/school_detail.html
{% extends "basicApp_base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to school detail page</h1>
    <h2>School details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students: </h3>

    {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old</p>
    {% endfor %}

</div>

<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

templates/school_form.html
{% extends "basicApp_base.html" %}
{% block body_block %}

<h1>{% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>

{% endblock %}

templates/school_list.html
{% extends "basicApp_base.html" %}

{% block body_block %}

<h1>Welcome to list of all schools!</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}